import Head from 'next/head';
import { Card } from 'react-bootstrap';
import axios from 'axios';
import { toast } from 'react-toastify';

import { EmailAlertForm } from '../components/EmailAlertForm';

const Home = () => {
  const handleSave = async (data) => {
    try {
      await axios.post('/api/email-alert/save', data);
      toast.success('Save Success!');
    } catch (e) {
      console.log(e);
      toast.error('Error while saving!');
    }
  };

  const handleTestAlert = async (data) => {
    try {
      await axios.post('/api/email-alert/test', data);
      toast.success('Test Success!');
    } catch (e) {
      console.log(e);
      toast.error('Error while testing!');
    }
  };

  return (
    <div className="py-4">
      <Head>
        <title>LogDNA Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card className="m-auto" style={{ maxWidth: 600 }}>
        <Card.Body>
          <Card.Title className="fw-bold">Email Alert</Card.Title>
          <div className="p-2 p-md-4">
            <EmailAlertForm onSave={handleSave} onTestAlert={handleTestAlert} />
          </div>
        </Card.Body>
      </Card>
    </div>
  );
};

export default Home;
